# Generated by Django 5.1.7 on 2025-03-23 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_usercollection_delete_todoitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preprocessed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='children',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='frequency_of_use',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='swiping_history',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='usercollection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.userbase'),
        ),
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField()),
                ('context', models.CharField(max_length=200)),
                ('usercollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userbase')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
