# Generated by Django 5.1.7 on 2025-03-23 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_userbase_created_at_alter_userbase_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usercollection',
            new_name='userbase',
        ),
    ]
