# Generated by Django 5.1.7 on 2025-03-24 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_usercollection_user_userbase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfeature',
            old_name='usercollection',
            new_name='userbase',
        ),
    ]
