# Generated by Django 5.1.7 on 2025-05-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('degree', models.CharField(max_length=200, null=True)),
                ('children', models.BooleanField(default=False)),
                ('relationship_status', models.CharField(max_length=200, null=True)),
                ('politics', models.CharField(max_length=200, null=True)),
                ('religion', models.CharField(max_length=200, null=True)),
                ('substances_alcohol', models.BooleanField(default=False, null=True)),
                ('substances_cannabis', models.BooleanField(default=False, null=True)),
                ('substances_nicotine', models.BooleanField(default=False, null=True)),
                ('age_importance', models.CharField(max_length=200, null=True)),
                ('degree_importance', models.CharField(max_length=200, null=True)),
                ('children_importance', models.CharField(max_length=200, null=True)),
                ('ethnicity_importance', models.CharField(max_length=200, null=True)),
                ('politics_importance', models.CharField(max_length=200, null=True)),
                ('religion_importance', models.CharField(max_length=200, null=True)),
                ('height_importance', models.CharField(max_length=200, null=True)),
                ('age_expected_lower_bound', models.IntegerField(null=True)),
                ('age_expected_upper_bound', models.IntegerField(null=True)),
            ],
        ),
    ]
