# Generated by Django 5.1.7 on 2025-05-06 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_userprofile_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
