# Generated by Django 5.1.7 on 2025-05-25 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('preprocessed', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('verified', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('height', models.FloatField(null=True)),
                ('interests', models.TextField(null=True)),
                ('looking_for', models.CharField(max_length=200, null=True)),
                ('children', models.BooleanField(default=False, null=True)),
                ('education_level', models.CharField(max_length=200, null=True)),
                ('occupation', models.CharField(max_length=200, null=True)),
                ('swiping_history', models.IntegerField(null=True)),
                ('frequency_of_use', models.CharField(max_length=200, null=True)),
                ('userbase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.userbase')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_vector', models.JSONField()),
                ('context', models.CharField(max_length=200)),
                ('userbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userbase')),
            ],
        ),
    ]
